# Generated by Django 4.2.10 on 2025-03-20 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('faculty_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.batch')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classsection')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
            ],
            options={
                'db_table': 'faculty_subject',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('faculty_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.facultysubject')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('credits', models.IntegerField()),
                ('has_theory', models.BooleanField(default=True)),
                ('has_lab', models.BooleanField(default=False)),
                ('is_elective', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.subject'),
        ),
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('elective_id', models.AutoField(primary_key=True, serialize=False)),
                ('elective_group', models.CharField(max_length=50)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.subject')),
            ],
            options={
                'db_table': 'elective_subjects',
            },
        ),
        migrations.CreateModel(
            name='BulkImportLog',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_import_logs',
            },
        ),
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('room_number', 'start_time', 'day_of_week', 'academic_year'), name='unique_room_time_day'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('faculty_subject', 'start_time', 'day_of_week', 'academic_year'), name='unique_faculty_time_day'),
        ),
        migrations.AddConstraint(
            model_name='facultysubject',
            constraint=models.UniqueConstraint(fields=('faculty', 'subject', 'class_section', 'batch', 'academic_year', 'is_lab'), name='unique_faculty_subject_class_batch_year'),
        ),
        migrations.AddConstraint(
            model_name='electivesubject',
            constraint=models.UniqueConstraint(fields=('subject',), name='unique_subject_elective'),
        ),
    ]
